version: '3.7'
container_name: solidarizr-mysql
volumes:
  data:
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USER}
      - MYSQL_DATABASE=${DB_PASS}